//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculationHistory
    {
        public int CalcID { get; set; }
        public Nullable<double> Field1 { get; set; }
        public Nullable<double> Field2 { get; set; }
        public Nullable<int> OperationID { get; set; }
        public Nullable<double> Result { get; set; }
        public Nullable<System.DateTime> CalcDate { get; set; }
    
        public virtual Operation Operation { get; set; }
    }
}
